package com.rayneo.mathcosmos

import android.content.Context
import android.media.MediaPlayer
import android.os.Bundle
import android.os.Handler
import android.os.Looper
import android.speech.tts.TextToSpeech
import android.speech.tts.UtteranceProgressListener
import android.util.Log
import java.io.File
import java.util.Locale

/**
 * Multi-voice crew announcer for the M.S.V. Mote. Each role speaks with a
 * distinct voice and sits in its own place in the stereo field (Engineering
 * left, the Physiologist right, the Pilot centre) so the bridge feels populated.
 *
 * Preferred source: pre-generated Fish Audio S2-pro clips bundled at
 *   assets/voice/<role>/<clipKey>.ogg   (Opus, generated by tools/generate_fish_audio.py; .wav also accepted)
 * Fallbacks, in order: a Fish clip cached from an earlier run, live Fish
 * synthesis (key + voice ids from BuildConfig), then Android TextToSpeech with
 * a per-role pitch/rate/voice so the crew still sound like different people.
 *
 * [onLineStart] fires (main thread) the moment a line actually begins playing —
 * not when it is queued — so captions stay in step with the audio.
 */
class CrewVoices(private val context: Context) {

    enum class Role(
        val folder: String,
        val label: String,
        val pitch: Float,
        val rate: Float,
        val voiceIndex: Int,
        val panLeft: Float,
        val panRight: Float
    ) {
        NAVIGATION("navigation", "HELM", 1.00f, 1.00f, 0, 1.00f, 1.00f),
        SCIENCE("science", "DOC", 1.14f, 0.98f, 1, 0.62f, 1.00f),
        ENGINEERING("engineering", "ENGINEERING", 0.82f, 0.95f, 2, 1.00f, 0.62f),
        COMPUTER("computer", "MOTE", 1.28f, 1.06f, 3, 1.00f, 1.00f)
    }

    private class Clip(val file: File, val role: Role, val text: String)

    private var tts: TextToSpeech? = null
    @Volatile private var ready = false
    private var player: MediaPlayer? = null
    private var currentRole: Role = Role.NAVIGATION
    private val clipQueue = ArrayDeque<Clip>()
    private var busy = false
    private val main = Handler(Looper.getMainLooper())
    /** Bumped by silence()/shutdown(): a live Fish fetch started before it must not play. */
    private var generation = 0
    private var closed = false
    private val ttsLines = HashMap<String, Pair<Role, String>>()
    private var ttsSeq = 0

    /** Called on the main thread when a line starts playing (clip or TTS). */
    var onLineStart: ((Role, String) -> Unit)? = null

    /** 0..1 dialogue gain from the audio-mix cycler (applied live to the current line and to TTS). */
    @Volatile var dialogueVolume = 1f
        set(value) {
            field = value.coerceIn(0f, 1f)
            val muted = field <= 0.001f
            main.post {
                applyVolume()
                if (muted) runCatching { tts?.stop() }
            }
        }

    private companion object {
        const val TAG = "MCVoice"
        val BUNDLED_FORMATS = arrayOf("ogg", "wav")
    }

    fun init() {
        if (tts != null) return
        closed = false
        invalidateStaleCache()
        val engine = TextToSpeech(context) { status ->
            if (status == TextToSpeech.SUCCESS) {
                runCatching { tts?.language = Locale.US }
                ready = true
                Log.i(TAG, "TTS ready")
            } else {
                Log.w(TAG, "TTS unavailable (status=$status) — relying on Fish/clip audio")
            }
        }
        engine.setOnUtteranceProgressListener(object : UtteranceProgressListener() {
            override fun onStart(utteranceId: String?) {
                main.post { ttsLines[utteranceId]?.let { (r, t) -> onLineStart?.invoke(r, t) } }
            }
            override fun onDone(utteranceId: String?) { main.post { ttsLines.remove(utteranceId) } }
            @Deprecated("Deprecated in Java")
            override fun onError(utteranceId: String?) { main.post { ttsLines.remove(utteranceId) } }
        })
        tts = engine
    }

    /**
     * Bundled clips are copied into the cache once and replayed from there. When the APK is
     * updated (new or re-rendered clips) those copies would be stale, so every cached voice,
     * Fish and sfx file is dropped whenever the package's update time changes.
     */
    private fun invalidateStaleCache() {
        val stamp = runCatching {
            context.packageManager.getPackageInfo(context.packageName, 0).lastUpdateTime
        }.getOrDefault(0L)
        val prefs = context.getSharedPreferences("voice_cache", Context.MODE_PRIVATE)
        if (prefs.getLong("apk_stamp", -1L) == stamp) return
        val removed = context.cacheDir.listFiles { f ->
            f.name.startsWith("voice_") || f.name.startsWith("fish_") || f.name.startsWith("sfx_")
        }?.count { it.delete() } ?: 0
        prefs.edit().putLong("apk_stamp", stamp).apply()
        Log.i(TAG, "APK updated: dropped $removed cached clips")
    }

    /**
     * Speak [text] in [role]'s voice. Priority:
     *   1) bundled clip  assets/voice/<role>/<clipKey>.wav
     *   2) previously fetched Fish Audio clip cached on disk
     *   3) live Fish Audio synthesis (key + voice id from BuildConfig)
     *   4) on-device TextToSpeech
     */
    fun speak(role: Role, text: String, clipKey: String? = null) {
        if (closed) return
        // Dynamic (clipKey-less) lines still get a stable cache key from their text.
        val key = clipKey ?: "dyn_${(role.name + "|" + text).hashCode()}"
        // Nothing gets cut mid-line. Helm/engineering just queue AHEAD of the Doc.
        val highPriority = role != Role.SCIENCE
        Log.i(TAG, "speak ${role.name} key=$key priority=$highPriority")
        if (playBundled(role, key, text, highPriority)) return
        if (playFile(fishCacheFile(role, key), role, text, highPriority)) return
        if (BuildConfig.FISH_API_KEY.isNotBlank() && voiceIdFor(role).isNotBlank()) {
            fetchFishThenPlay(role, text, key, highPriority)
            return
        }
        if (ttsAvailable()) { speakTts(role, text); return }
        speakSilently(role, text)
    }

    /** True only if there is a speech engine that could actually say something. */
    private fun ttsAvailable(): Boolean = tts != null && ready

    /**
     * Nothing can say this line — no bundled clip, no cached clip, no Fish key, and on the X3 Pro
     * no speech engine bound at all. Show it anyway.
     *
     * Without this the ride is not merely silent, it is BLANK: captions are driven by the moment a
     * line actually starts playing, so a tour whose voices have not been generated yet would run
     * with nothing on screen and no way to tell it apart from a broken script. Reporting the line
     * and holding "busy" for roughly as long as it would take to say keeps the whole timing model
     * — captions, silence-filling banter, the director's pacing — behaving exactly as it will once
     * the audio exists.
     */
    private fun speakSilently(role: Role, text: String) {
        val spoken = text.replace(Regex("\\[[^\\]]*\\]"), " ").replace(Regex("\\s+"), " ").trim()
        if (spoken.isEmpty()) return
        val gen = generation
        busy = true
        main.post { onLineStart?.invoke(role, text) }
        // About two and a half words a second, the pace the crew actually speak at.
        val ms = (spoken.split(' ').size / 2.5f * 1000f).toLong().coerceAtLeast(1200L)
        main.postDelayed({ if (gen == generation) { busy = false; playNextQueued() } }, ms)
    }

    private fun voiceIdFor(role: Role): String = when (role) {
        Role.NAVIGATION -> BuildConfig.FISH_VOICE_NAVIGATION
        Role.SCIENCE -> BuildConfig.FISH_VOICE_SCIENCE
        Role.ENGINEERING -> BuildConfig.FISH_VOICE_ENGINEERING
        Role.COMPUTER -> BuildConfig.FISH_VOICE_SCIENCE
    }

    private fun fishCacheFile(role: Role, key: String) =
        File(context.cacheDir, "fish_${role.folder}_$key.mp3")

    private fun fetchFishThenPlay(role: Role, text: String, key: String, interrupt: Boolean) {
        val gen = generation
        Thread {
            val bytes = FishAudioClient.synthesize(
                BuildConfig.FISH_API_KEY, BuildConfig.FISH_MODEL, voiceIdFor(role), text
            )
            main.post {
                // A jump, pause or shutdown happened while we were fetching: drop the stale line.
                if (gen != generation || closed) return@post
                if (bytes != null && bytes.size > 256) {
                    val f = fishCacheFile(role, key)
                    runCatching { f.writeBytes(bytes) }
                    if (!playFile(f, role, text, interrupt)) speakTts(role, text)
                } else {
                    speakTts(role, text)
                }
            }
        }.apply { isDaemon = true }.start()
    }

    private fun speakTts(role: Role, text: String) {
        val engine = tts ?: return
        if (!ready || closed || dialogueVolume <= 0.001f) return
        engine.setPitch(role.pitch)
        engine.setSpeechRate(role.rate)
        pickVoice(engine, role)
        // Strip the Fish acting tags ([warm], [awe]...) so TTS doesn't read them aloud.
        val spoken = text.replace(Regex("\\[[^\\]]*\\]"), " ").replace(Regex("\\s+"), " ").trim()
        if (spoken.isEmpty()) return
        val id = "crew_${role.name}_${ttsSeq++}"
        ttsLines[id] = role to text
        val params = Bundle().apply { putFloat(TextToSpeech.Engine.KEY_PARAM_VOLUME, dialogueVolume) }
        // Queue (never flush) so TTS lines don't cut each other off either.
        engine.speak(spoken, TextToSpeech.QUEUE_ADD, params, id)
    }

    /**
     * Copy a bundled asset clip to cache (atomically) and play it. Looks for the compact
     * OGG Vorbis clip first, then a WAV. False if neither asset exists.
     */
    private fun playBundled(role: Role, key: String, text: String, interrupt: Boolean): Boolean {
        for (ext in BUNDLED_FORMATS) {
            val cacheFile = File(context.cacheDir, "voice_${role.folder}_$key.$ext")
            if (!cacheFile.exists() || cacheFile.length() == 0L) {
                val tmp = File(context.cacheDir, "voice_${role.folder}_$key.$ext.tmp")
                try {
                    context.assets.open("voice/${role.folder}/$key.$ext").use { input ->
                        tmp.outputStream().use { output -> input.copyTo(output) }
                    }
                    if (!tmp.renameTo(cacheFile)) { tmp.delete(); continue }
                } catch (e: Exception) {
                    tmp.delete()
                    continue // not bundled in this format
                }
            }
            return playFile(cacheFile, role, text, interrupt)
        }
        return false
    }

    /** Queue or immediately play an on-disk clip. False if missing/empty. */
    private fun playFile(file: File, role: Role, text: String, highPriority: Boolean): Boolean {
        if (closed) return false
        if (!file.exists() || file.length() < 128L) return false
        val clip = Clip(file, role, text)
        if (!busy) {
            startClip(clip)                       // nothing playing -> play immediately
        } else {
            // Never cut a clip in progress. Priority only sets queue ORDER:
            // helm/engineering jump ahead of any queued science.
            if (highPriority) clipQueue.addFirst(clip) else clipQueue.addLast(clip)
            while (clipQueue.size > 4) clipQueue.removeLast()
        }
        return true
    }

    private fun startClip(clip: Clip) {
        runCatching { player?.release() }
        player = null
        val mp = MediaPlayer()
        try {
            mp.setDataSource(clip.file.absolutePath)
        } catch (e: Exception) {
            runCatching { mp.release() }
            runCatching { clip.file.delete() }     // a bad cache file must not be replayed forever
            busy = false; playNextQueued(); return
        }
        currentRole = clip.role
        mp.setOnCompletionListener { it.release(); if (player === it) player = null; busy = false; playNextQueued() }
        mp.setOnErrorListener { p, _, _ -> runCatching { p.release() }; if (player === p) player = null; busy = false; playNextQueued(); true }
        mp.setOnPreparedListener {
            if (player !== it) { runCatching { it.release() }; return@setOnPreparedListener }   // silenced meanwhile
            it.setVolume(dialogueVolume * clip.role.panLeft, dialogueVolume * clip.role.panRight)
            it.start()
            onLineStart?.invoke(clip.role, clip.text)
        }
        player = mp
        busy = true
        mp.prepareAsync()
    }

    private fun applyVolume() {
        val p = player ?: return
        runCatching { p.setVolume(dialogueVolume * currentRole.panLeft, dialogueVolume * currentRole.panRight) }
    }

    private fun playNextQueued() {
        val next = clipQueue.removeFirstOrNull() ?: return
        startClip(next)
    }

    private fun pickVoice(engine: TextToSpeech, role: Role) {
        val voices = runCatching {
            engine.voices?.filter { it.locale?.language == Locale.US.language && !it.isNetworkConnectionRequired }
        }.getOrNull()?.sortedBy { it.name } ?: return
        if (voices.isEmpty()) return
        runCatching { engine.voice = voices[role.voiceIndex % voices.size] }
    }

    /** True while a clip is playing or queued, or TTS is talking. */
    fun isSpeaking(): Boolean {
        // Only ask the speech engine if there is one. The X3 Pro has none, and the director polls
        // this ten times a second — unguarded it logs "not bound to TTS engine" ten times a second
        // for the whole ride, which buries every other line in the log and costs a binder call each.
        val ttsSpeaking = ready && runCatching { tts?.isSpeaking == true }.getOrDefault(false)
        return busy || clipQueue.isNotEmpty() || ttsSpeaking
    }

    /** Stop any current line + clear the queue, but keep TTS alive (segment jumps, pause). */
    fun silence() {
        generation++
        runCatching { tts?.stop() }
        ttsLines.clear()
        clipQueue.clear()
        runCatching { player?.release() }
        player = null
        busy = false
    }

    fun shutdown() {
        closed = true
        generation++
        runCatching { tts?.stop(); tts?.shutdown() }
        tts = null
        ready = false
        ttsLines.clear()
        clipQueue.clear()
        busy = false
        runCatching { player?.release() }
        player = null
    }
}
